# Generated by Django 4.2.2 on 2023-06-26 16:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_image', models.ImageField(upload_to='new_images')),
                ('preview_image', models.ImageField(upload_to='new_images/previews')),
                ('text', models.TextField()),
                ('publication_date', models.DateField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
