# Generated by Django 4.2.2 on 2023-06-27 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_direction', models.CharField(max_length=50)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.place')),
            ],
        ),
    ]
